## YAML Template.
---
# src/main/resources/application.yml for Product Service
server:
  port: 5004 # A unique port for this microservice
 
# Set logging level to debug BUT REMOVE IN PRODUCTION      
logging:
 level:
  org.springframework.security: DEBUG

truststore:
  path: classpath:backend_truststore.p12
  password: ${truststore.password} # -> microservicetrustpass@123+@+
  
spring:
  application:
    name: logistics-media-service # The unique name of this service, used by Eureka
  config:
    import: "vault://secret/aliwudi-marketplace"
    
  cloud:
    vault:
      uri: http://localhost:8200
      token: root
      kv:
        enabled: true
        
    
  security:
    oauth2:
      resourceserver:
        jwt:
          # This issuer-uri is good for matching the 'iss' claim in the JWT.
          # It also allows Spring to attempt discovery of JWKS via .well-known/openid-configuration if available.
          issuer-uri: https://localhost:8443 # Replace with your Auth Server's actual issuer URI

          # THIS IS CRUCIAL FOR SIGNATURE VERIFICATION.
          # It tells Spring Security where to fetch the public keys (JWKS) to validate the JWT's signature.
          # This should point to the JWK Set endpoint of your Authorization Server.
          jwk-set-uri: https://localhost:8443/realms/chuks-emaketplace-realm/protocol/openid-connect/certs # Example for Keycloak
          
  # RabbitMQ Connection Details for user-service
  rabbitmq:
    host: localhost # Change if RabbitMQ is on a different host
    port: 5672
    # Rabbitmq username and password loaded from Vault
    username: ${rabbitmq.username} # -> guest # TODO
    password: ${rabbitmq.password} # -> guest #TODO

          
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/ # Pointing to your Eureka Server
  instance:
    hostname: localhost # For local development, use localhost
    prefer-ip-address: true # Optional: Register with IP address instead of hostname (good for containerized envs)
    

jwt:
  auth:
    converter:
      resource-id: emaketplace-app
      principle-attribute: preferred_username
      
      