package com.aliwudi.marketplace.backend.common.dto.event;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

/**
 * Event for requesting an email verification OTP.
 * This event would be published by the user-service after user registration.
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
public class SmsVerificationRequestedEvent {
    private String authServerUserId; // Keycloak ID of the user
    private String phoneNumber;
    private String name; // For personalization in the email
    private String otpCode; // NEW: The actual OTP generated by the user-service

}
