## YAML Template.
---
# src/main/resources/application.yml for User Service

server:
  port: 5001 # A unique port for this microservice

app:
  host: https://localhost
  
# Your backend's callback URIs for social logins
# IMPORTANT: These must match EXACTLY what you configure in Google/Facebook developer consoles  
  social:
    google:
      redirect-uri: https://your-backend.com/api/auth/google/callback
    facebook:
      redirect-uri: https://your-backend.com/api/auth/facebook/callback
  # Your frontend's deep link scheme (adjust as per your native app)
  frontend:
    redirect-scheme: your-native-app-scheme://auth   
    
    
truststore:
  path: classpath:backend_truststore.p12
  password: microservicetrustpass@123+@+

spring:
  application:
    name: user-service # The unique name of this service, used by Eureka

  security:
    oauth2:
      resourceserver:
        jwt:
          # This issuer-uri is good for matching the 'iss' claim in the JWT.
          # It also allows Spring to attempt discovery of JWKS via .well-known/openid-configuration if available.
          issuer-uri: https://localhost:8443 # Replace with your Auth Server's actual issuer URI

          # THIS IS CRUCIAL FOR SIGNATURE VERIFICATION.
          # It tells Spring Security where to fetch the public keys (JWKS) to validate the JWT's signature.
          # This should point to the JWK Set endpoint of your Authorization Server.
          jwk-set-uri: https://localhost:8443/realms/chuks-emaketplace-realm/protocol/openid-connect/certs # Example for Keycloak


  # RabbitMQ Connection Details for user-service
  rabbitmq:
    host: localhost # Change if RabbitMQ is on a different host
  rabbitmq:
    port: 5672
  rabbitmq:
    username: guest # TODO
  rabbitmq:
    password: guest #TODO


  # Redis Configuration (REQUIRED for EmailVerificationService for OTP storage)
  # Ensure your Redis instance is running and accessible.
  data:
    redis:
      host: localhost # Your Redis server host
      port: 6379 # Your Redis server port
      password: # Leave empty if no password, or provide your Redis password
      timeout: 5s # Connection timeout
      database: 0 # Redis database index (default is 0)

# Keycloak/Authorization Server Configuration
auth-server:
  url: https://localhost:8443 # Your Authorization Server URL (e.g., Keycloak URL)
  auth-url: http://localhost:8443/auth
  realm: chuks-emaketplace-realm # The realm where your application users reside
  resource: your-spring-boot-client-id # The client ID of your Spring Boot app in Keycloak
  
  # Configuration for the backend service to call Authorization Server Admin API
  admin:
    url: https://localhost:8443 # Authorization Server Admin URL (e.g., Keycloak Admin URL)
    realm: master # Realm where your admin client (e.g., admin-cli or a custom client for this service) resides
    client-id: admin-cli # The client ID this service will use to get an admin token
    client-secret: YOUR_KEYCLOAK_ADMIN_CLI_SECRET # The secret for the admin-cli or your custom admin client.
                                                  # IMPORTANT: For 'admin-cli', you might need to enable 'Service Accounts Enabled'
                                                  # and get the secret from the 'Credentials' tab.
                                                  # For production, create a dedicated confidential client for this service
                                                  # with 'Service Accounts Enabled' and appropriate realm-management roles.

# Removed redundant Keycloak admin properties for clarity and consolidation:
# admin-cli-client-id: admin-cli
# admin-username: admin
# admin-password: admin
# admin-auth-server-url: https://localhost:8443
# admin-realm: chuks-emaketplace-realm
# admin-service-client-id: user-service-admin-client
# admin-service-client-secret: YOUR_GENERATED_USER_SERVICE_ADMIN_CLIENT_SECRET


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/ # Pointing to your Eureka Server
  instance:
    hostname: localhost # For local development, use localhost
    prefer-ip-address: true # Optional: Register with IP address instead of hostname (good for containerized envs)

jwt:
  auth:
    converter:
      resource-id: emaketplace-app
      principle-attribute: preferred_username
      


