# Server Configuration
server.port: 5002

# Truststore Configuration
truststore.path: classpath:backend_truststore.p12
truststore.password: ${truststore.password} # -> microservicetrustpass@123+@+

# Spring Application
spring.application.name: order-processing-service
spring.config.import: vault://secret/aliwudi-marketplace

# Vault Configuration
spring.cloud.vault.uri: http://127.0.0.1:8200
spring.cloud.vault.authentication: APPROLE
spring.cloud.vault.app-role.role-id: ${VAULT_ROLE_ID}
spring.cloud.vault.app-role.secret-id: ${VAULT_SECRET_ID}
spring.cloud.vault.app-role.role: aliwudi-marketplace-role
spring.cloud.vault.app-role.app-role-path: approle

# Spring Security OAuth2 Resource Server (JWT)
spring.security.oauth2.resourceserver.jwt.issuer-uri: https://localhost:8443
spring.security.oauth2.resourceserver.jwt.jwk-set-uri: https://localhost:8443/realms/chuks-emaketplace-realm/protocol/openid-connect/certs

# RabbitMQ Configuration
spring.rabbitmq.host: localhost
spring.rabbitmq.port: 5672
spring.rabbitmq.username: ${rabbitmq.username} # -> guest
spring.rabbitmq.password: ${rabbitmq.password} # -> guest

# Eureka Client Configuration
eureka.client.service-url.defaultZone: http://localhost:8761/eureka/
eureka.instance.hostname: localhost
eureka.instance.prefer-ip-address: true

# JWT Auth Converter
jwt.auth.converter.resource-id: emaketplace-app
jwt.auth.converter.principle-attribute: preferred_username
