# Server Configuration
server.port: 8761

# Truststore Configuration
truststore.path: classpath:backend_truststore.p12
truststore.password: ${truststore.password} # -> microservicetrustpass@123+@+

# Spring Application
spring.application.name: eureka-server
spring.config.import: vault://secret/aliwudi-marketplace

# Vault Configuration
spring.cloud.vault.uri: http://localhost:8200
spring.cloud.vault.token: root
spring.cloud.vault.kv.enabled: true

# Logging Configuration (REMOVE OR INCREASE LEVEL IN PRODUCTION)
logging.level.org.springframework.security: DEBUG

# Eureka Server Configuration
eureka.instance.hostname: localhost
eureka.instance.ip-address: 127.0.0.1
eureka.instance.prefer-ip-address: true

eureka.client.register-with-eureka: false
eureka.client.fetch-registry: false
eureka.client.service-url.defaultZone: http://localhost:8761/eureka/
